# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-23 13:00
from __future__ import unicode_literals
from django.db import migrations
from django.contrib.auth.hashers import make_password
from django.conf import settings


def create_superuser(apps, schema_editor):
    user_model = apps.get_model('accounts.User')
    user = user_model()
    user.username = settings.USERNAME
    user.first_name = settings.FIRST_NAME
    user.last_name = settings.LAST_NAME
    user.email = settings.EMAIL
    user.password = make_password(settings.PASSWORD)
    user.is_superuser = True
    user.is_staff = True
    user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
