# Generated by Django 2.0 on 2017-12-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=140)),
                ('image', models.URLField()),
                ('content', models.TextField()),
                ('all_content', models.TextField()),
                ('original_all_content', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('comments', models.URLField(blank=True, null=True)),
                ('categories', models.ManyToManyField(null=True, to='blog.Category')),
            ],
        ),
    ]
