# Generated by Django 2.0 on 2017-12-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='categories',
            field=models.ManyToManyField(to='blog.Category'),
        ),
    ]
