# Generated by Django 2.0 on 2017-12-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
