# Generated by Django 2.0 on 2017-12-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_publication_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='like',
            new_name='likes',
        ),
    ]
