# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-23 13:00
from __future__ import unicode_literals
from django.db import migrations
from blog.services import load_publications
from django.conf import settings


def load_publications_from_blog(apps, schema_editor):
    if settings.TEST:
        # These migration should not run in the tests
        return
    publication_model = apps.get_model('blog.Publication')
    # This migration was made only for de purpose of the test
    # the load of de data should be made in a worker.
    load_publications(publication_model)


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0008_auto_20171215_2326'),
    ]

    operations = [
        migrations.RunPython(load_publications_from_blog),
    ]
